### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by TWille** [Pflanzrausch/pflanzrausch.github.io#1]
Hi, super Initiative, würde das gerne weiter teilen. Ist das als Open Source Projekt gedacht? 
so als CC-BY oder MIT Lizenz ggf.? wär super

**Comment by TWille** [comment]
https://opensource.guide/de/legal/ hilft sicher

**Comment by SkyGuardian42** [comment]
Vielen Dank für dein Feedback, das ganze soll Open Source sein, deshalb habe ich in d7da96f8402fdfbcb1cd1f06f20dddbbd83e2b91 der Website die CC BY-SA Lizenz hinzugefügt!

**Comment by TWille** [comment]
4.0 international oder 2.0? verlinkt ist 2.0 → im Repo die LICENSE.md hatte ich gemeint, aber klar auf der Seite vermerkt ist auch super, ggf. Link zum Repo (ich habs auch so gefunden, aber wäre schneller wenn wer mitwirken mag) 

Hier hab ich mal eine schöne CC-BY-SA Markdown Datei hinterlegt (copy RAW) → allerdings 4.0!
Vielleicht hilfts ja.

https://github.com/opencultureagency/ASKotec/blob/master/LICENSE.md

Ich schicks auf jeden Fall mal rum in Kürze, danke

**Comment by SkyGuardian42** [comment]
Nochmal vielen Dank, die Lizenz ist jetzt überall auf Version 4.0 aktualisiert.
